### ISSUE TITLE
Workflow tips for HDA authoring?

### ISSUE THREAD

**Issue by melMass** [christophercrouzet/nvidia-warp-houdini#1]
Hi Christophe, 

Thanks a lot for this wrapper ( 😅 ) of warp!
I really like how it's packaged, and I since read your article on the subject (https://christophercrouzet.com/blog/dev/authoring-houdini-hdas)

I was wondering if you had tips in order to go from HDA to code "easily"?
I tried a few approaches around the `hou.Node.asCode` functions and I think that with more time I will get something working.

For now I'm using "unpacked" HDAs but I face the drawbacks mentioned in your article (bad diffing, different houdini licenses etc...)

Thanks

**Comment by christophercrouzet** [comment]
Hi @melMass!

Thanks for your kind words!

To my knowledge, there is no way built into Houdini that converts existing HDAs into code that looks satisfactory. But maybe I'm just being picky :sweat_smile:

In any case, I've always been handcrafting the code, so no magic trick here, and I don't mind it that way (at the exception that I wished it was more straightforward using Houdini's API, since it can quickly get messy unless you write a framework to streamline some common operations).

That being said, it *should* be possible to generate code from an existing network. But it would take some efforts and the result likely won't be as good as some handcrafted code. Except maybe if the code is written against a custom framework that allows authoring node with a declarative API.

I'll be closing this issue since it's not an issue per se but feel free to keep commenting here if you like!
